# Generated by Django 4.1.5 on 2023-02-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_user_id_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_rating',
            field=models.FloatField(),
        ),
    ]
