# Generated by Django 4.1.5 on 2023-02-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_movie_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_genres',
            field=models.ManyToManyField(related_name='movies', to='backend.genre'),
        ),
    ]
